---
title: "CNVscan for SRP199233"
author: "Mark Ziemann"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
theme: cosmo
---

## Intro

Here we're doing an analysis to identify CNV using normalised reads counts across genomic windows.

```{r,libs}

library("cobs")
library("quantreg")
library("parallel")
library("gplots")
library("dplyr")
library("kableExtra")

```

```{r,interpolate}

interpolate_points<-function(row,dat,curve){
  MY_X=dat[row,1]
  MY_Y=dat[row,2]
  VAL1=tail(which(curve[,1]<MY_X),1)
  VAL2=VAL1+1
  X <- curve[c(VAL1,VAL2),1]
  Y <- curve[c(VAL1,VAL2),2]
  INTERP_Y=approx(X,Y,xout=MY_X)$y
  INTERP_Y
}

```

## 1 Mbp bins

```{r,1mb1, fig.width = 8 ,fig.height = 8}

x <- read.table("SRP199233.1e6_fmt.tsv",header=T,row.names=1)
x <- x[which(rowSums(x)>=10),]
x <- sweep(x, 2, colSums(x), FUN="/")*1000000
mysd <- apply(x,1,sd)
mean <- apply(x,1,mean)
y <- data.frame(log10(mean),mysd/mean)
colnames(y) <- c("logMean","cv")
Rbs.9 <- cobs(y$logMean,y$cv, nknots=10,constraint="none",tau=0.99)
Rbs.median <- cobs(y$logMean,y$cv,nknots=10,constraint="none",tau=0.5)
pred <- data.frame(predict(Rbs.9))

res <- mclapply(X=1:nrow(y),function(row) {
  interpolate_points(row,y,pred)
  },mc.cores=8)
y$interpolated <- unlist(res)

y$diff <-  y$cv-y$interpolated
yy <- y[order(-y$diff),]
yy <- head(yy,50)

write.table(yy,file="SRP199233.1e6_regions.tsv")

yy %>% kbl() %>% kable_paper("hover", full_width = F)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV")
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 25)
zz <- x[which(rownames(x) %in% rownames(yy)),]
heatmap.2(as.matrix(zz),margin=c(8, 22),cexRow=0.65,trace="none",
  cexCol=0.8,col=my_palette,scale="row")

heatmap.2(cor(t(zz)),trace="none",scale="none",margins=c(12,12),
  cexRow=0.8, cexCol=0.8)

```

Now fixed up a bit.

```{r,1mb2, fig.width = 8 ,fig.height = 8}

x <- read.table("SRP199233.1e6_fmt.tsv",header=T,row.names=1)

x <- x[grep("X",rownames(x),invert=TRUE),]
x <- x[grep("Y",rownames(x),invert=TRUE),]
x <- x[grep("M",rownames(x),invert=TRUE),]
x <- x[grep("J",rownames(x),invert=TRUE),]
x <- x[grep("G",rownames(x),invert=TRUE),]

x <- x[which(rowSums(x)>=10),]
x <- sweep(x, 2, colSums(x), FUN="/")*1000000
mysd <- apply(x,1,sd)
mean <- apply(x,1,mean)
y <- data.frame(log10(mean),mysd/mean)
colnames(y) <- c("logMean","cv")
Rbs.9 <- cobs(y$logMean,y$cv, nknots=10,constraint="none",tau=0.99)
Rbs.median <- cobs(y$logMean,y$cv,nknots=10,constraint="none",tau=0.5)
pred <- data.frame(predict(Rbs.9))

res <- mclapply(X=1:nrow(y),function(row) {
  interpolate_points(row,y,pred)
  },mc.cores=8)
y$interpolated <- unlist(res)

y$diff <- y$cv-y$interpolated
yy <- y[order(-y$diff),]
yy <- head(yy,50)

write.table(yy,file="SRP199233.1e6_regions.tsv")

yy %>% kbl() %>% kable_paper("hover", full_width = F)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV")
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
#text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV",xlim=c(1,4.5),ylim=c(0,0.3))
#lines(predict(Rbs.9), col = "red", lwd = 1.0)
#lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 25)
zz <- x[which(rownames(x) %in% rownames(yy)),]
heatmap.2(as.matrix(zz),margin=c(8, 22),cexRow=0.65,trace="none",
  cexCol=0.8,col=my_palette,scale="row")

heatmap.2(cor(t(zz)),trace="none",scale="none",margins=c(12,12),
  cexRow=0.8, cexCol=0.8)

for (i in 1:19){
mychr=as.character(i)
regex=paste("^",mychr,":",sep="")
chr <- x[grep(regex,rownames(x)),]
mymax = max(chr)
plot(chr[,1], xaxt = "n", pch=19, col="gray",
  ylim=c(0,mymax),ylab="RPM of 1Mbp bins of chr",main=mychr)
axis(1, at=chr[,1], labels=rownames(chr), xlab="chr", las=1)
points( chr[,1], xaxt = "n", las=1, pch=19, col="gray"  )
points( chr[,2], xaxt = "n", las=1, pch=19, col="lightblue"  )
points( chr[,3], xaxt = "n", las=1, pch=19, col="lightgreen"  )
points( chr[,4], xaxt = "n", las=1, pch=19, col="pink" )
points( chr[,5], xaxt = "n", las=1, pch=19, col="orange" )
points( chr[,6], xaxt = "n", las=1, pch=19, col="black" )
grid()
}

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  mymedian <- median(rowMeans(chr))
  mymax <- max(rowMeans(chr))
  rat <- mymax / mymedian
  return(c(mymax,mymedian,rat))
})

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  top <- head(chr[order(-rowMeans(chr)),])
  return(top)
})

```



## 100 kbp bins

```{r,100kbp1, fig.width = 8 ,fig.height = 8}

x<-read.table("SRP199233.1e5_fmt.tsv",header=T,row.names=1)

x <- x[grep("X",rownames(x),invert=TRUE),]
x <- x[grep("Y",rownames(x),invert=TRUE),]
x <- x[grep("M",rownames(x),invert=TRUE),]
x <- x[grep("J",rownames(x),invert=TRUE),]
x <- x[grep("G",rownames(x),invert=TRUE),]

x <- x[which(rowSums(x)>=10),]
x <- sweep(x, 2, colSums(x), FUN="/")*1000000
mysd <- apply(x,1,sd)
mean <- apply(x,1,mean)
y <- data.frame(log10(mean),mysd/mean)
colnames(y) <- c("logMean","cv")
Rbs.9 <- cobs(y$logMean,y$cv, nknots=10,constraint="none",tau=0.99)
Rbs.median <- cobs(y$logMean,y$cv,nknots=10,constraint="none",tau=0.5)
pred <- data.frame(predict(Rbs.9))

res <- mclapply(X=1:nrow(y),function(row) {
  interpolate_points(row,y,pred)
  },mc.cores=8)
y$interpolated <- unlist(res)

y$diff <- y$cv-y$interpolated
yy1 <- y[order(-y$diff),]
yy1 <- head(yy,50)
yy2 <- subset(y,logMean>2 & cv>0.05)
yy <- rbind(yy1,yy2)

write.table(yy,file="SRP199233.1e5_regions.tsv")

yy %>% kbl() %>% kable_paper("hover", full_width = F)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV")
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
#text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV",xlim=c(1,4.5),ylim=c(0,0.35))
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 25)
zz <- x[which(rownames(x) %in% rownames(yy)),]
heatmap.2(as.matrix(zz),margin=c(8, 22),cexRow=0.65,trace="none",
  cexCol=0.8,col=my_palette,scale="row")

heatmap.2(cor(t(zz)),trace="none",scale="none",margins=c(12,12),
  cexRow=0.8, cexCol=0.8)

for (i in 1:19){
mychr=as.character(i)
regex=paste("^",mychr,":",sep="")
chr <- x[grep(regex,rownames(x)),]
mymax = max(chr)
plot(chr[,1], xaxt = "n", pch=19, col="gray",
  ylim=c(0,mymax),ylab="RPM of 100 kbp bins of chr",main=mychr)
axis(1, at=chr[,1], labels=rownames(chr), xlab="chr", las=1)
points( chr[,1], xaxt = "n", las=1, pch=19, col="gray"  )
points( chr[,2], xaxt = "n", las=1, pch=19, col="lightblue"  )
points( chr[,3], xaxt = "n", las=1, pch=19, col="lightgreen"  )
points( chr[,4], xaxt = "n", las=1, pch=19, col="pink" )
points( chr[,5], xaxt = "n", las=1, pch=19, col="orange" )
points( chr[,6], xaxt = "n", las=1, pch=19, col="black" )
grid()
}

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  mymedian <- median(rowMeans(chr))
  mymax <- max(rowMeans(chr))
  rat <- mymax / mymedian
  return(c(mymax,mymedian,rat))
})

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  top <- head(chr[order(-rowMeans(chr)),])
  return(top)
})

```

## 10 kbp bins

```{r,10kbp1, fig.width = 8 ,fig.height = 8}

x<-read.table("SRP199233.1e4_fmt.tsv",header=T,row.names=1)

x <- x[grep("X",rownames(x),invert=TRUE),]
x <- x[grep("Y",rownames(x),invert=TRUE),]
x <- x[grep("M",rownames(x),invert=TRUE),]
x <- x[grep("J",rownames(x),invert=TRUE),]
x <- x[grep("G",rownames(x),invert=TRUE),]

x <- x[which(rowSums(x)>=10),]
x <- sweep(x, 2, colSums(x), FUN="/")*1000000
mysd <- apply(x,1,sd)
mean <- apply(x,1,mean)
y <- data.frame(log10(mean),mysd/mean)
colnames(y) <- c("logMean","cv")
Rbs.9 <- cobs(y$logMean,y$cv, nknots=10,constraint="none",tau=0.99)
Rbs.median <- cobs(y$logMean,y$cv,nknots=10,constraint="none",tau=0.5)
pred <- data.frame(predict(Rbs.9))

res <- mclapply(X=1:nrow(y),function(row) {
  interpolate_points(row,y,pred)
  },mc.cores=8)
y$interpolated <- unlist(res)

y$diff <- y$cv-y$interpolated
yy <- y[order(-y$diff),]
yy1 <- head(yy,20)
yy2 <- subset(y,logMean>1 & cv>0.05)
yy <- rbind(yy1,yy2)

write.table(yy,file="SRP199233.1e4_regions.tsv")

yy %>% kbl() %>% kable_paper("hover", full_width = F)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV")
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
#text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV",xlim=c(0,4.5),ylim=c(0,1))
lines(predict(Rbs.9), col = "red", lwd = 1.0)
lines(predict(Rbs.median), col = "blue", lwd = 1.0)
points(yy$logMean,yy$cv)
#text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 25)
zz <- x[which(rownames(x) %in% rownames(yy)),]
heatmap.2(as.matrix(zz),margin=c(8, 22),cexRow=0.65,trace="none",
  cexCol=0.8,col=my_palette,scale="row")

heatmap.2(cor(t(zz)),trace="none",scale="none",margins=c(12,12),
  cexRow=0.8, cexCol=0.8)

for (i in 1:19){
mychr=as.character(i)
regex=paste("^",mychr,":",sep="")
chr <- x[grep(regex,rownames(x)),]
mymax = max(chr)
plot(chr[,1], xaxt = "n", pch=19, col="gray",
  ylim=c(0,mymax),ylab="RPM of 10 kbp bins of chr",main=mychr)
axis(1, at=chr[,1], labels=rownames(chr), xlab="chr", las=1)
points( chr[,1], xaxt = "n", las=1, pch=19, col="gray"  )
points( chr[,2], xaxt = "n", las=1, pch=19, col="lightblue"  )
points( chr[,3], xaxt = "n", las=1, pch=19, col="lightgreen"  )
points( chr[,4], xaxt = "n", las=1, pch=19, col="pink" )
points( chr[,5], xaxt = "n", las=1, pch=19, col="orange" )
points( chr[,6], xaxt = "n", las=1, pch=19, col="black" )
grid()
}

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  mymedian <- median(rowMeans(chr))
  mymax <- max(rowMeans(chr))
  rat <- mymax / mymedian
  return(c(mymax,mymedian,rat))
})

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  top <- head(chr[order(-rowMeans(chr)),])
  return(top)
})

```

## 1 kbp bins

```{r,1kbp1, fig.width = 8 ,fig.height = 8, eval=TRUE}

x <- read.table("SRP199233.1e3_fmt.tsv",header=T,row.names=1)

x <- x[grep("X",rownames(x),invert=TRUE),]
x <- x[grep("Y",rownames(x),invert=TRUE),]
x <- x[grep("M",rownames(x),invert=TRUE),]
x <- x[grep("J",rownames(x),invert=TRUE),]
x <- x[grep("G",rownames(x),invert=TRUE),]

x <- x[which(rowSums(x)>=6),]
x <- sweep(x, 2, colSums(x), FUN="/")*1000000
mysd <- apply(x,1,sd)
mean <- apply(x,1,mean)
y <- data.frame(log10(mean),mysd/mean)
colnames(y) <- c("logMean","cv")

yy <- subset(y,cv > 0.2 & logMean > 0.3)

write.table(yy,file="SRP199233.1e3_regions.tsv")

yy %>% kbl() %>% kable_paper("hover", full_width = F)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV")
points(yy$logMean,yy$cv)
#text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

plot(y$logMean,y$cv,pch=18,cex=0.5,xlab="log10(mean)",ylab="CV",xlim=c(0,4.5),ylim=c(0,1))
points(yy$logMean,yy$cv)
text(yy$logMean,yy$cv+0.02,labels=rownames(yy),cex=0.8)

my_palette <- colorRampPalette(c("blue", "white", "red"))(n = 25)
zz <- x[which(rownames(x) %in% rownames(yy)),]
heatmap.2(as.matrix(zz),margin=c(8, 22),cexRow=0.65,trace="none",
  cexCol=0.8,col=my_palette,scale="row")

heatmap.2(cor(t(zz)),trace="none",scale="none",margins=c(12,12),
  cexRow=0.8, cexCol=0.8)

for (i in 1:19){
mychr=as.character(i)
regex=paste("^",mychr,":",sep="")
chr <- x[grep(regex,rownames(x)),]
mymax = max(chr)
plot(chr[,1], xaxt = "n", pch=19, col="gray",
  ylim=c(0,mymax),ylab="RPM of 1 kbp bins of chr",main=mychr)
axis(1, at=chr[,1], labels=rownames(chr), xlab="chr", las=1)
points( chr[,1], xaxt = "n", las=1, pch=19, col="gray"  )
points( chr[,2], xaxt = "n", las=1, pch=19, col="lightblue"  )
points( chr[,3], xaxt = "n", las=1, pch=19, col="lightgreen"  )
points( chr[,4], xaxt = "n", las=1, pch=19, col="pink" )
points( chr[,5], xaxt = "n", las=1, pch=19, col="orange" )
points( chr[,6], xaxt = "n", las=1, pch=19, col="black" )
grid()
}

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  mymedian <- median(rowMeans(chr))
  mymax <- max(rowMeans(chr))
  rat <- mymax / mymedian
  return(c(mymax,mymedian,rat))
})

lapply(1:19,function(i){
  mychr=as.character(i)
  regex=paste("^",mychr,":",sep="")
  chr <- x[grep(regex,rownames(x)),]
  top <- head(chr[order(-rowMeans(chr)),])
  return(top)
})

```

## Session information

```{r,session}

sessionInfo()

```
